version: '3'

services:
  contacts:
    image: public.ecr.aws/amazoncorretto/amazoncorretto:21.0.1-al2023-headful
    environment:
      - DB_USERNAME=admin
      - DB_PASSWORD=pass1234
    volumes:
      - ./contacts-0.0.1-SNAPSHOT.jar:/app/contacts-0.0.1-SNAPSHOT.jar
    command: ["java", "-jar", "/app/contacts-0.0.1-SNAPSHOT.jar", "--spring.profiles.active=prod"]
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - contacts
    networks:
      - app_network

networks:
  app_network:
